import type { Metadata } from 'next';
import { Manrope, Space_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const sans = Manrope({
    variable: '--font-sans',
    subsets: ['latin'],
});

const mono = Space_Mono({
    variable: '--font-mono',
    subsets: ['latin'],
    weight: ['400'],
});

export const metadata: Metadata = {
    title: 'Proto',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${sans.variable} ${mono.variable} antialiased w-full h-screen bg-gradient-to-br from-[#00b4db] to-[#0083b0] p-8 sm:p-20`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
